### ISSUE TITLE
Can not reproduce the reported MRR results on FB15K-237 using MLP 

### ISSUE THREAD

**Issue by wdimmy** [amayuelas/NNKGReasoning#1]
**The  MRR results reported in the paper for FB15K-237:**
             2p   &  3p   &   2i      &    3i   &    ip   &   pi     &   2u   &  up
MLP & 12.4 &  10.6  &  31.7 &  43.9 &  14.9  &  24.2 &  13.7  &  9.7 

**The  MRR results comes from my trained model for FB15K-237:**
MLP_{real}  & 9.6 &  8.9  &  23.2 &  32.4 &  9.8  &  16.6 &  10.1  &  8.4 

I absolutely follow the default parameters you reporte in the paper, but I can not achieve the comparable results reported in the paper,  could you give me some hints on the training?

**Comment by amayuelas** [comment]
I believe that your only problem is that you have not trained the models long enough. Just to give you an idea, the mlp model took me 3-4 days to train on 450,000 iterations.

I have just trained a model for a few hours and I'm getting the following MRR. You can imagine these results get closer to the numbers reported in the paper as we increase the training time: 

**Script**

`CUDA_VISIBLE_DEVICES=0 python main.py --cuda --do_train --do_valid --do_test 
  --data_path data/FB15k-237-betae -n 128 -b 512 -d 800 -g 24 
  -lr 0.0001 --max_steps 450001 --cpu_num 1 --geo mlp --valid_steps 15000 
  --tasks "1p.2p.3p.2i.3i.ip.pi.2u.up" &`

**Results (1p.2p.3p.2i.3i.ip.pi.2u.up)**

> Test 1p MRR at step 30000: 0.405807
> Test 2p MRR at step 30000: 0.104181
> Test 3p MRR at step 30000: 0.093051
> ...

The number of tasks that you are using should not really be a problem, maybe it takes a bit longer to train. 
Below you can see the results for the mlp model trained on _1p.2p.3p.2i.3i.ip.pi.2in.3in.inp.pin.pni.2u.up_

**Results (1p.2p.3p.2i.3i.ip.pi.2in.3in.inp.pin.pni.2u.up)**

> Test 1p MRR at step 450000: 0.420141
> Test 2p MRR at step 450000: 0.123844
> Test 3p MRR at step 450000: 0.105049

**Comment by wdimmy** [comment]
Hi,

Thanks for your reply.

We used the parameters reported in your appendix B, where the where the leraning rate(=0.0005) and the margin values (=60) are different from that of your script above. 

I will used the script you mentioned above to re run the experiment. 

Best
