### ISSUE TITLE
Out of memory issue for  the MLP_mix model on FB15-237

### ISSUE THREAD

**Issue by wdimmy** [amayuelas/NNKGReasoning#2]
As you mention in the paper "All experiments have been computed on independent processes on NVIDIA GPUs, either the
GeForce GTX Titan X Pascal (12 GB) or the Tesla T4 (16 GB).". However, when I ran MLP_mix on FB15-237 datasets using Titan(12GB), it is out of memory.

**Comment by amayuelas** [comment]
There was indeed an error when I cleaned the code and copied it into the public repo. 
The Mixer Blocks need to be smaller to fit in memory. 
It has already been fixed and updated with the parameters we used in the paper.
