### ISSUE TITLE
Some questions about the MRR of the experimental results

### ISSUE THREAD

**Issue by Vin1115** [amayuelas/NNKGReasoning#4]
Hello, May I ask if the experimental results of EPFO queries are only trained on EPFO queries(1p.2p.3p.2i.3i.ip.pi.2u.up)? 
And are the results of the experiment on negative queries trained on the full FOL queries or just the queries that contains only negation operations(2in.3in.inp.pin.pni)? Looking forward to your reply!

**Comment by amayuelas** [comment]
You are correct. 
They EPFO queries are trained only with EPFO queries. 
While the set including negative queries are trained with all queries. 
This is done to compare fairly with our baselines.
